#include "SeGroupID.hpp"


struct SEGROUPINFO
{
    GAMETEXT::VALUE m_TextID;
    bool m_bCallFreeFlag;
    bool m_bHelpFlag;
};


static const SEGROUPINFO s_aSeGroupID[] =
{
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x45E),   false,  true    },
    { GAMETEXT::VALUE(0x45F),   false,  true    },
    { GAMETEXT::VALUE(0x460),   false,  true    },
    { GAMETEXT::VALUE(0x460),   false,  true    },
    { GAMETEXT::VALUE(0x461),   false,  true    },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x462),   true,   true    },
    { GAMETEXT::VALUE(0x463),   true,   true    },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  true    },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x464),   false,  true    },
    { GAMETEXT::VALUE(0x465),   false,  true    },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x466),   false,  true    },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x467),   false,  true    },
    { GAMETEXT::VALUE(0x468),   false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x469),   false,  true    },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46A),   false,  true    },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46A),   true,   true    },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46B),   false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46C),   true,   true    },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x46D),   true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46E),   false,  true    },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x46F),   false,   true   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x470),   false,   true   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x471),   false,   true   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x472),   false,  false   },
    { GAMETEXT::VALUE(0x473),   false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x460),   false,   true   },
    { GAMETEXT::VALUE(0x0),     true,   false   },
    { GAMETEXT::VALUE(0x474),   false,   true   },
    { GAMETEXT::VALUE(0x474),   false,   true   },
    { GAMETEXT::VALUE(0x475),   false,   true   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x0),     false,  false   },
    { GAMETEXT::VALUE(0x474),   false,   true   },
    { GAMETEXT::VALUE(0x476),   false,  false   },
    { GAMETEXT::VALUE(0x477),   false,  false   },
    { GAMETEXT::VALUE(0x478),   false,  false   },
    { GAMETEXT::VALUE(0x479),   false,  false   },
    { GAMETEXT::VALUE(0x47A),   false,  false   },
};


static inline const SEGROUPINFO& GetSeGroupInfo(SEGROUPID::VALUE id)
{
    ASSERT(id >= 0 && id < COUNT_OF(s_aSeGroupID));
    return s_aSeGroupID[id];
};


namespace SEGROUPID
{
    bool IsHelpID(VALUE id)
    {
        return GetSeGroupInfo(id).m_bHelpFlag;
    };
    

    bool IsCallFree(VALUE id)
    {
        return GetSeGroupInfo(id).m_bCallFreeFlag;
    };


    GAMETEXT::VALUE GetGameText(VALUE id)
    {
        return GetSeGroupInfo(id).m_TextID;
    };
};