#pragma once

#include "SdTypes.hpp"


#define SD_CODE_DRVCTRL             (SD_CODE_CTRL_MIN)

#define SD_CODE_DRVCTRL_ALLOFF      (SD_CODE_DRVCTRL + 0)
#define SD_CODE_DRVCTRL_BGMOFF      (SD_CODE_DRVCTRL + 1)
#define SD_CODE_DRVCTRL_PAUSESET    (SD_CODE_DRVCTRL + 2)
#define SD_CODE_DRVCTRL_PAUSECLR    (SD_CODE_DRVCTRL + 3)
#define SD_CODE_DRVCTRL_STEREO      (SD_CODE_DRVCTRL + 4)
#define SD_CODE_DRVCTRL_MONO        (SD_CODE_DRVCTRL + 5)
#define SD_CODE_DRVCTRL_SURSET      (SD_CODE_DRVCTRL + 6)
#define SD_CODE_DRVCTRL_FADEOUT1    (SD_CODE_DRVCTRL + 7)
#define SD_CODE_DRVCTRL_FADEOUT2    (SD_CODE_DRVCTRL + 8)
#define SD_CODE_DRVCTRL_FADEOUT3    (SD_CODE_DRVCTRL + 9)
#define SD_CODE_DRVCTRL_FADEOUTALL  (SD_CODE_DRVCTRL + 10)
#define SD_CODE_DRVCTRL_TEMPOUPSET  (SD_CODE_DRVCTRL + 11)
#define SD_CODE_DRVCTRL_TEMPOUPCLR  (SD_CODE_DRVCTRL + 12)
#define SD_CODE_DRVCTRL_VOLDOWNSET  (SD_CODE_DRVCTRL + 13)
#define SD_CODE_DRVCTRL_VOLDOWNCLR  (SD_CODE_DRVCTRL + 14)
#define SD_CODE_DRVCTRL_FADEOUTALLX (SD_CODE_DRVCTRL + 15)
#define SD_CODE_DRVCTRL_VOXFADEOUT  (SD_CODE_DRVCTRL + 16)
#define SD_CODE_DRVCTRL_VOXFADEOUT2 (SD_CODE_DRVCTRL + 17)
#define SD_CODE_DRVCTRL_VOXOFF      (SD_CODE_DRVCTRL + 18)
#define SD_CODE_DRVCTRL_VOXCLR      (SD_CODE_DRVCTRL + 19)
#define SD_CODE_DRVCTRL_VOXREVON    (SD_CODE_DRVCTRL + 20)
#define SD_CODE_DRVCTRL_VOXREVOFF   (SD_CODE_DRVCTRL + 21)
#define SD_CODE_DRVCTRL_VOXCORON    (SD_CODE_DRVCTRL + 22)
#define SD_CODE_DRVCTRL_VOXCOROFF   (SD_CODE_DRVCTRL + 23)
#define SD_CODE_DRVCTRL_VOXCORNO    (SD_CODE_DRVCTRL + 24)
#define SD_CODE_DRVCTRL_VAGREVON    (SD_CODE_DRVCTRL + 25)
#define SD_CODE_DRVCTRL_VAGREVOFF   (SD_CODE_DRVCTRL + 26)
#define SD_CODE_DRVCTRL_VAGCORON    (SD_CODE_DRVCTRL + 27)
#define SD_CODE_DRVCTRL_VAGCOROFF   (SD_CODE_DRVCTRL + 28)
#define SD_CODE_DRVCTRL_VAGCORNO    (SD_CODE_DRVCTRL + 29)
#define SD_CODE_DRVCTRL_PRGFADEOUT  (SD_CODE_DRVCTRL + 30)
#define SD_CODE_DRVCTRL_PRGOFF      (SD_CODE_DRVCTRL + 31)


extern SdSetDriverCode_t SdDrvNextCodeBuffer;
extern int32 SdDrvVolumeDownData;
extern int32 SdDrvVolumeDownSpeed;
extern int32 SdDrvAllFadeOutData;
extern int32 SdDrvAllFadeOutSpeed;
extern bool SdDrvPause;
extern bool SdDrvStereoFlag;
extern int32 SdDrvTempoUpSpeed;
extern int32 SdDrvTempoUpData;

void SdDrvCtrlFunc(int32 _code, uint32 _param1, uint32 _param2);