#pragma once


namespace GIMMICKID
{
    enum VALUE
    {
        ID_INVALID = 0,

        SYSTEMSTART = 0x1,
        ID_S_ANDSWI = SYSTEMSTART,
        ID_S_GROUP,
        ID_S_GCLEAR,
        ID_S_GOVER,
        ID_S_MOVIE,
        ID_S_CAMERA,
        ID_S_EVCAM,
        ID_S_SOUND,
        ID_S_WALL,
        ID_S_FALLPT,
        ID_S_RESET,
        ID_S_HELP,
        ID_S_TUTO,
        ID_S_EKILL,
        SYSTEMEND,

        EVENTSTART = 0x20,
        ID_E_PDEAD = EVENTSTART,
        ID_E_TIME,
        ID_E_EBRK,
        ID_E_EBRKAL,
        ID_E_PWALL,
        ID_E_PSPHER,
        ID_E_PVOLUM,
        ID_E_GBRK,
        ID_E_EWALL,
        ID_E_UTRVOL,
        ID_E_DONLSR,
        ID_E_RRSPHR,
        ID_E_FTWALL,
        EVENTEND,

        GENERATORSTART = 0x30,
        ID_G_SET = GENERATORSTART,
        ID_G_GROUND,
        ID_G_AIR,
        ID_G_EGG,
        ID_G_CAVE,
        ID_G_DOOR,
        ID_G_CAR,
        ID_G_SSHIPS,
        GENERATOREND,

        NORMALSTART = 0x40,
        ID_N_THROW = NORMALSTART,
        ID_N_ITEMBX,
        ID_N_BRKCAR,
        ID_N_BRKOBJ,
        ID_N_ROLOBJ,
        ID_N_MVFLLI,
        ID_N_MVFLPA,
        ID_N_MVFLRO,
        ID_N_CONSOL,
        ID_N_SWITCH,
        ID_N_SWIPIL,
        ID_N_BRKPIL,
        ID_N_SHKPIL,
        ID_N_NORPIL,
        ID_N_RAPROC,
        ID_N_LEOS,
        ID_N_LEOM,
        ID_N_LEOL,
        ID_N_GRASS,
        ID_N_CRYSTL,
        ID_N_GUILLO,
        ID_N_SEESAW,
        ID_N_FALOBJ,
        ID_N_METEO,
        ID_N_DOOR,
        ID_N_UTROM,
        ID_N_LASER,
        ID_N_MINE,
        ID_N_BELCON,
        ID_N_STOPER,
        NORMALEND,

        RIDESTART = 0x70,
        ID_R_FLAG = RIDESTART,
        ID_R_THNDER,
        ID_R_ASTRID,
        ID_R_SHUTTR,
        RIDEEND,

        OTHERSTART = 0x80,
        ID_N_ITEM = OTHERSTART,
        OTHEREND,

        MAPSTART = 0x90,
        ID_N_LIGHT = MAPSTART,
        ID_N_WEATHER,
        ID_N_SMOKE,
        ID_N_FLAME,
        ID_N_STEAM,
        ID_N_SPARK,
        ID_N_MOTH,
        ID_N_FISH,
        ID_N_BUBBLE,
        ID_N_MIST,
        ID_N_SPLASH,
        ID_N_EXP,
        MAPEND,

        KOYUUSTART = 0xA0,
        ID_K_M12N = KOYUUSTART,
        ID_K_M02N,
        ID_K_M05N,
        ID_K_M38B,
        ID_K_M38BMAN,
        ID_K_M17N,
        ID_K_M43N,
        ID_K_M28NGR,
        ID_K_M28NPT,
        ID_K_M28NPR,
        ID_K_M28OB,
        ID_K_M28OBR,
        ID_K_M28OBRM,
        ID_K_M44N,
        ID_K_M44NM,
        ID_K_M50NB,
        ID_K_M23N,
        ID_K_M04N,
        ID_K_M20F,
        ID_K_M53F,
        KOYUUEND,
    };
};