#pragma once


namespace SECRETID
{
    enum VALUE
    {
        ID_NONE = 0,
        ID_FIRST = 1,
        
        CHARACTERSTART = ID_FIRST,
        ID_CHARACTER_CASEY = CHARACTERSTART,
        ID_CHARACTER_SPLINTER,
        ID_CHARACTER_KARAI,
        ID_CHARACTER_SLASHUUR,
        CHARACTERMAX,

        HOMESTART = CHARACTERMAX,
        ID_HOME_SHOP = HOMESTART,
        ID_HOME_TOURNAMENT_KITTY,
        ID_HOME_TOURNAMENT_MONSTER,
        ID_HOME_TOURNAMENT_FOOT,
        ID_HOME_TOURNAMENT_BATTLENEXUS,
        ID_HOME_BONUSMATERIAL,
        ID_HOME_ARCADEGAME,
        ID_HOME_SAMURAI_LEO,    // costume
        ID_HOME_SAMURAI_RAP,    // costume
        ID_HOME_SAMURAI_MIC,    // costume
        ID_HOME_SAMURAI_DON,    // costume
        ID_HOME_NEXUS_LEO,      // costume
        ID_HOME_NEXUS_RAP,      // costume
        ID_HOME_NEXUS_MIC,      // costume
        ID_HOME_NEXUS_DON,      // costume
        HOMEMAX,

        ID_SEARCH_ANTIQUE = HOMEMAX,        
        ID_POWERUP_ATTACK,
        ID_POWERUP_DEFENCE,

        PASSWORDSTART,
        ID_PASSWORD_CHEATCODE_MIGHTYTURTLE = PASSWORDSTART,
        ID_PASSWORD_CHEATCODE_HEALTH,
        ID_PASSWORD_CHEATCODE_PIZZAPARADISE,
        ID_PASSWORD_CHEATCODE_SELFRECOVERY,
        ID_PASSWORD_CHEATCODE_SHURIKEN,
        ID_PASSWORD_CHEATCODE_SUPERATTACK,
        ID_PASSWORD_CHEATCODE_SUPERDEFENCE,
        ID_PASSWORD_CHALLENGE_ENDURANCE,
        ID_PASSWORD_CHALLENGE_SHURIKEN,
        ID_PASSWORD_CHALLENGE_FATALBLOW,
        ID_PASSWORD_CHALLENGE_ABYSS,
        ID_PASSWORD_CHALLENGE_POISON,
        ID_PASSWORD_CHALLENGE_SUPERTOUGH,
        ID_PASSWORD_CHALLENGE_NIGHTMARE,
        ID_PASSWORD_CHEATCODE_TODDLING,
        ID_PASSWORD_CHEATCODE_SQUEAKING,        
        ID_PASSWORD_GAMEBOY_SECRET_1,
        ID_PASSWORD_GAMEBOY_SECRET_2,
        ID_PASSWORD_GAMEBOY_SECRET_3,
        ID_PASSWORD_GAMEBOY_SECRET_4,
        ID_PASSWORD_GAMEBOY_SECRET_5,
        PASSWORDMAX,

        DATABASESTART = PASSWORDMAX,
        ID_DATABASE_LEO_A = DATABASESTART,
        ID_DATABASE_LEO_B,
        ID_DATABASE_SLASHUUR,
        ID_DATABASE_RAP_A,
        ID_DATABASE_RAP_B,
        ID_DATABASE_CASEY,
        ID_DATABASE_MIC_A,
        ID_DATABASE_MIC_B,
        ID_DATABASE_KARAI,
        ID_DATABASE_DON_A,
        ID_DATABASE_DON_B,
        ID_DATABASE_SPLINTER,
        ID_DATABASE_APRIL,
        ID_DATABASE_USAGI,
        ID_DATABASE_SHREDDER,
        ID_DATABASE_DRAKO,
        ID_DATABASE_RATS,
        ID_DATABASE_TRAXIMUS,
        ID_DATABASE_LEATHERHEAD,
        ID_DATABASE_ELITE,
        ID_DATABASE_SPASMOSAUR,
        ID_DATABASE_HUN,
        ID_DATABASE_ULTIMATE,
        ID_DATABASE_SECONDARY_A,
        ID_DATABASE_SECONDARY_B,
        ID_DATABASE_OTHERS,
        ID_DATABASE_NY,
        ID_DATABASE_DHOONNIB,
        ID_DATABASE_JAPAN,
        ID_DATABASE_KURAIYAMA,
        ID_DATABASE_ANOTHER_DIMENSION,
        ID_DATABASE_VEHICLES,
        ID_DATABASE_ANIMS,
        ID_DATABASE_CG,
        ID_DATABASE_PLAYMATES,
        ID_DATABASE_PROMOTION_ARTS,        
        DATABASEMAX,
        NORMALMAX = DATABASEMAX,        

        SECRETSTART = DATABASEMAX,
        CHEATCODESTART = DATABASEMAX,
        ID_CHEATCODE_MIGHTYTURTLE = CHEATCODESTART,
        ID_CHEATCODE_HEALTH,
        ID_CHEATCODE_PIZZAPARADISE,
        ID_CHEATCODE_SELFRECOVERY,
        ID_CHEATCODE_SHURIKEN,
        ID_CHEATCODE_SUPERATTACK,
        ID_CHEATCODE_SUPERDEFENCE,
        CHEATCODEMAX,

        CHALLENGESTART = CHEATCODEMAX,
        ID_CHALLENGE_ENDURANCE = CHALLENGESTART,
        ID_CHALLENGE_SHURIKEN,
        ID_CHALLENGE_FATALBLOW,
        ID_CHALLENGE_ABYSS,
        ID_CHALLENGE_POISON,
        ID_CHALLENGE_SUPERTOUGH,
        ID_CHALLENGE_NIGHTMARE,
        CHALLENGEMAX,
        
        ID_TODDLING = CHALLENGEMAX,
        ID_SQUEAKING,
        SECRETMAX,
        
        ID_MAX = SECRETMAX,
    };
};