#include "StageInfo.hpp"

#include "System/Common/File/FileID.hpp"


struct STAGEINFO
{
    const char*              m_pszName;
    int32                    m_iFileID;
    MAPID::VALUE             m_MapID;
    int32                    m_iBgmNo;
    AREAID::VALUE            m_AreaID;
    GAMETYPES::STAGEMODE     m_mode;
    CStageInfo::CAMERAUPDATE m_cameraupdate;
};


static const STAGEINFO s_aStageInfo[] =
{
    //
    //  Normal
    //
    { "NONE",   FILEID::ID_INVALID, MAPID::ID_NONE,     SDCODE_BGM(0x3000),     AREAID::ID_NONE,    GAMETYPES::STAGEMODE_NONE,      CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST01T",  FILEID::ID_ST01T,   MAPID::ID_M01T,     SDCODE_BGM(0x3000),     AREAID::ID_AREA01,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST02N",  FILEID::ID_ST02N,   MAPID::ID_M02N,     SDCODE_BGM(0x3000),     AREAID::ID_AREA02,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST02NB", FILEID::ID_ST02NB,  MAPID::ID_M02NB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA02,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST03S",  FILEID::ID_ST03S,   MAPID::ID_M03S,     SDCODE_BGM(0x3014),     AREAID::ID_AREA03,  GAMETYPES::STAGEMODE_HOME,      CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST04N",  FILEID::ID_ST04N,   MAPID::ID_M04N,     SDCODE_BGM(0x3001),     AREAID::ID_AREA04,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST04NB", FILEID::ID_ST04NB,  MAPID::ID_M04NB,    SDCODE_BGM(0x3001),     AREAID::ID_AREA04,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST05N",  FILEID::ID_ST05N,   MAPID::ID_M05N,     SDCODE_BGM(0x3001),     AREAID::ID_AREA05,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST06R",  FILEID::ID_ST06R,   MAPID::ID_M06R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA06,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,      },
    { "ST09N",  FILEID::ID_ST09N,   MAPID::ID_M09N,     SDCODE_BGM(0x3002),     AREAID::ID_AREA09,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST10N",  FILEID::ID_ST10N,   MAPID::ID_M10N,     SDCODE_BGM(0x3002),     AREAID::ID_AREA10,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST11J",  FILEID::ID_ST11J,   MAPID::ID_M11J,     SDCODE_BGM(0x3002),     AREAID::ID_AREA11,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST12N",  FILEID::ID_ST12N,   MAPID::ID_M12N,     SDCODE_BGM(0x3003),     AREAID::ID_AREA12,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST13R",  FILEID::ID_ST13R,   MAPID::ID_M13R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA13,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,      },
    { "ST14N",  FILEID::ID_ST14N,   MAPID::ID_M14N,     SDCODE_BGM(0x3003),     AREAID::ID_AREA14,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST15N",  FILEID::ID_ST15N,   MAPID::ID_M15N,     SDCODE_BGM(0x3004),     AREAID::ID_AREA15,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST17N",  FILEID::ID_ST17N,   MAPID::ID_M17N,     SDCODE_BGM(0x301B),     AREAID::ID_AREA17,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST18F",  FILEID::ID_ST18F,   MAPID::ID_M18F,     SDCODE_BGM(0x3005),     AREAID::ID_AREA18,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST18FB", FILEID::ID_ST18FB,  MAPID::ID_M18FB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA18,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST19N",  FILEID::ID_ST19N,   MAPID::ID_M19N,     SDCODE_BGM(0x3006),     AREAID::ID_AREA19,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST20F",  FILEID::ID_ST20F,   MAPID::ID_M20F,     SDCODE_BGM(0x3006),     AREAID::ID_AREA20,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST20FB", FILEID::ID_ST20FB,  MAPID::ID_M20FB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA20,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST21N",  FILEID::ID_ST21N,   MAPID::ID_M21N,     SDCODE_BGM(0x3007),     AREAID::ID_AREA21,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST21NB", FILEID::ID_ST21NB,  MAPID::ID_M21NB,    SDCODE_BGM(0x301D),     AREAID::ID_AREA21,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST22R",  FILEID::ID_ST22R,   MAPID::ID_M22R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA22,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,      },
    { "ST23N",  FILEID::ID_ST23N,   MAPID::ID_M23N,     SDCODE_BGM(0x3008),     AREAID::ID_AREA23,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST24N",  FILEID::ID_ST24N,   MAPID::ID_M24N,     SDCODE_BGM(0x3009),     AREAID::ID_AREA24,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST25J",  FILEID::ID_ST25J,   MAPID::ID_M25J,     SDCODE_BGM(0x300A),     AREAID::ID_AREA25,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST26N",  FILEID::ID_ST26N,   MAPID::ID_M26N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA26,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST27N",  FILEID::ID_ST27N,   MAPID::ID_M27N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA27,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST28N",  FILEID::ID_ST28N,   MAPID::ID_M28N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA28,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST29N",  FILEID::ID_ST29N,   MAPID::ID_M29N,     SDCODE_BGM(0x300B),     AREAID::ID_AREA29,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST30N",  FILEID::ID_ST30N,   MAPID::ID_M30N,     SDCODE_BGM(0x300B),     AREAID::ID_AREA30,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST30NB", FILEID::ID_ST30NB,  MAPID::ID_M30NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA30,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST31NB", FILEID::ID_ST31NB,  MAPID::ID_M31NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA31,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST32R",  FILEID::ID_ST32R,   MAPID::ID_M32R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA32,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE       },
    { "ST33J",  FILEID::ID_ST33J,   MAPID::ID_M33J,     SDCODE_BGM(0x300C),     AREAID::ID_AREA33,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST34N",  FILEID::ID_ST34N,   MAPID::ID_M34N,     SDCODE_BGM(0x300D),     AREAID::ID_AREA34,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST35N",  FILEID::ID_ST35N,   MAPID::ID_M35N,     SDCODE_BGM(0x300D),     AREAID::ID_AREA35,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST36N",  FILEID::ID_ST36N,   MAPID::ID_M36N,     SDCODE_BGM(0x300C),     AREAID::ID_AREA36,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST37N",  FILEID::ID_ST37N,   MAPID::ID_M37N,     SDCODE_BGM(0x300C),     AREAID::ID_AREA37,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST38NB", FILEID::ID_ST38NB,  MAPID::ID_M38NB,    SDCODE_BGM(0x3019),     AREAID::ID_AREA38,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST39N",  FILEID::ID_ST39N,   MAPID::ID_M39N,     SDCODE_BGM(0x300E),     AREAID::ID_AREA39,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST40OB", FILEID::ID_ST40OB,  MAPID::ID_M40OB,    SDCODE_BGM(0x3019),     AREAID::ID_AREA40,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST41N",  FILEID::ID_ST41N,   MAPID::ID_M41N,     SDCODE_BGM(0x300F),     AREAID::ID_AREA41,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST42NB", FILEID::ID_ST42NB,  MAPID::ID_M42NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA42,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST43N",  FILEID::ID_ST43N,   MAPID::ID_M43N,     SDCODE_BGM(0x3010),     AREAID::ID_AREA43,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST44N",  FILEID::ID_ST44N,   MAPID::ID_M44N,     SDCODE_BGM(0x3010),     AREAID::ID_AREA44,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST44NB", FILEID::ID_ST44NB,  MAPID::ID_M44NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA44,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST45N",  FILEID::ID_ST45N,   MAPID::ID_M45N,     SDCODE_BGM(0x3011),     AREAID::ID_AREA45,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST46R",  FILEID::ID_ST46R,   MAPID::ID_M46R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA46,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,      },
    { "ST47O",  FILEID::ID_ST47O,   MAPID::ID_M47O,     SDCODE_BGM(0x3011),     AREAID::ID_AREA47,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST47OB", FILEID::ID_ST47OB,  MAPID::ID_M47OB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA47,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST48N",  FILEID::ID_ST48N,   MAPID::ID_M48N,     SDCODE_BGM(0x3012),     AREAID::ID_AREA48,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST49N",  FILEID::ID_ST49N,   MAPID::ID_M49N,     SDCODE_BGM(0x3012),     AREAID::ID_AREA49,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST50NB", FILEID::ID_ST50NB,  MAPID::ID_M50NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA50,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST52F",  FILEID::ID_ST52F,   MAPID::ID_M52F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA52,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST52FB", FILEID::ID_ST52FB,  MAPID::ID_M52FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA52,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST53F",  FILEID::ID_ST53F,   MAPID::ID_M53F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA53,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST53FB", FILEID::ID_ST53FB,  MAPID::ID_M53FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA53,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST54F",  FILEID::ID_ST54F,   MAPID::ID_M54F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA54,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST54FB", FILEID::ID_ST54FB,  MAPID::ID_M54FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA54,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST55F",  FILEID::ID_ST55F,   MAPID::ID_M55F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA55,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST55FB", FILEID::ID_ST55FB,  MAPID::ID_M55FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA55,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,    },
    { "ST56NB", FILEID::ID_ST56NB,  MAPID::ID_M56NB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA56,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST57NB", FILEID::ID_ST57NB,  MAPID::ID_M57NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA57,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST58OB1",FILEID::ID_ST58OB1, MAPID::ID_M58O,     SDCODE_BGM(0x3019),     AREAID::ID_AREA58,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},
    { "ST58OB2",FILEID::ID_ST58OB2, MAPID::ID_M58OB,    SDCODE_BGM(0x301A),     AREAID::ID_AREA58,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE,},

    //
    //  Kitty
    //
    { "ST60X_A01", FILEID::ID_ST60X_A01, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A02", FILEID::ID_ST60X_A02, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A03", FILEID::ID_ST60X_A03, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A04", FILEID::ID_ST60X_A04, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A05", FILEID::ID_ST60X_A05, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A06", FILEID::ID_ST60X_A06, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A07", FILEID::ID_ST60X_A07, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A08", FILEID::ID_ST60X_A08, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A09", FILEID::ID_ST60X_A09, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_A10", FILEID::ID_ST60X_A10, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },

    //
    //  Monster
    //
    { "ST60X_B01", FILEID::ID_ST60X_B01, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B02", FILEID::ID_ST60X_B02, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B03", FILEID::ID_ST60X_B03, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B04", FILEID::ID_ST60X_B04, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B05", FILEID::ID_ST60X_B05, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B06", FILEID::ID_ST60X_B06, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B07", FILEID::ID_ST60X_B07, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B08", FILEID::ID_ST60X_B08, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B09", FILEID::ID_ST60X_B09, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_B10", FILEID::ID_ST60X_B10, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },

    //
    //  Foot
    //
    { "ST60X_C01", FILEID::ID_ST60X_C01, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C02", FILEID::ID_ST60X_C02, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C03", FILEID::ID_ST60X_C03, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C04", FILEID::ID_ST60X_C04, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C05", FILEID::ID_ST60X_C05, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C06", FILEID::ID_ST60X_C06, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C07", FILEID::ID_ST60X_C07, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C08", FILEID::ID_ST60X_C08, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C09", FILEID::ID_ST60X_C09, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_C10", FILEID::ID_ST60X_C10, MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },

    //
    //  Battle Nexus
    //
    { "ST60X_D01", FILEID::ID_ST60X_D01, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D02", FILEID::ID_ST60X_D02, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D03", FILEID::ID_ST60X_D03, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D04", FILEID::ID_ST60X_D04, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D05", FILEID::ID_ST60X_D05, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D06", FILEID::ID_ST60X_D06, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D07", FILEID::ID_ST60X_D07, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D08", FILEID::ID_ST60X_D08, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D09", FILEID::ID_ST60X_D09, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },
    { "ST60X_D10", FILEID::ID_ST60X_D10, MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, },

    //
    //  Misc
    //
#ifdef _DEBUG    
    { "STTEST",    FILEID::ID_ST03S,     MAPID::ID_TEST, 0, AREAID::ID_NONE, GAMETYPES::STAGEMODE_NONE, CStageInfo::CAMERAUPDATE_NORMAL },
#else /* _DEBUG */
    { "STTEST",    FILEID::ID_INVALID,   MAPID::ID_TEST, 0, AREAID::ID_NONE, GAMETYPES::STAGEMODE_NONE, CStageInfo::CAMERAUPDATE_NORMAL },
#endif /* _DEBUG */
};


static_assert(COUNT_OF(s_aStageInfo) == STAGEID::ID_MAX, "update me");


static const STAGEINFO& StageInfo(STAGEID::VALUE idStage)
{    
    ASSERT(idStage >= STAGEID::ID_NONE);
    ASSERT(idStage < STAGEID::ID_MAX);

    return s_aStageInfo[idStage];
};


/*static*/ int32 CStageInfo::GetFileID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_iFileID;
};


/*static*/ MAPID::VALUE CStageInfo::GetMapID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_MapID;
};


/*static*/ int32 CStageInfo::GetBgmNo(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_iBgmNo;
};


/*static*/ AREAID::VALUE CStageInfo::GetAreaID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_AreaID;
};


/*static*/ GAMETYPES::STAGEMODE CStageInfo::GetMode(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_mode;
};


/*static*/ float CStageInfo::GetEnemyAppearDistance(STAGEID::VALUE idStage)
{
    if (idStage == STAGEID::ID_ST31NB)   // spasmosaur area
        return 200.0f;
    
    return 25.0f;
};


/*static*/ CStageInfo::CAMERAUPDATE CStageInfo::GetCameraUpdateType(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_cameraupdate;
};


/*static*/ float CStageInfo::GetObjectSleepDistance(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST23N:
        return 80.0f;

    case STAGEID::ID_ST34N:
    case STAGEID::ID_ST44NB:
        return 60.0f;

    case STAGEID::ID_ST52F:
    case STAGEID::ID_ST53F:
        return 50.0f;

    case STAGEID::ID_ST31NB:
        return 500.0f;

    default:
        return 40.0f;
    };
};


/*static*/ ENEMYID::VALUE CStageInfo::GetGaugeEnemyID(STAGEID::VALUE idStage, int32 iEnemyIndex)
{
    ENEMYID::VALUE enemyId = ENEMYID::ID_DUMMY;

    if (iEnemyIndex)
    {
        if ((idStage == STAGEID::ID_ST60X_C07) && (iEnemyIndex == 1))
            enemyId = ENEMYID::ID_ELITE_FOOT_B;

        return enemyId;
    };

    switch (idStage)
    {
#ifdef _DEBUG
    case STAGEID::ID_STTEST:
        enemyId = ENEMYID::ID_KARAI;
        break;
#endif /* _DEBUG */
        
    case STAGEID::ID_ST02NB:
        enemyId = ENEMYID::ID_HUN_A;
        break;

    case STAGEID::ID_ST18FB:
    case STAGEID::ID_ST60X_D04:
        enemyId = ENEMYID::ID_NINJA_RATS_A;
        break;
        
    case STAGEID::ID_ST20FB:
    case STAGEID::ID_ST50NB:
    case STAGEID::ID_ST60X_D08:
        enemyId = ENEMYID::ID_SLASSHUR;
        break;
        
    case STAGEID::ID_ST30NB:
    case STAGEID::ID_ST60X_D03:
        enemyId = ENEMYID::ID_TRAXIMUS;
        break;
        
    case STAGEID::ID_ST31NB:
        enemyId = ENEMYID::ID_SPASMOSAUR;
        break;
        
    case STAGEID::ID_ST38NB:
        enemyId = ENEMYID::ID_FEUDAL_JAPAN_SHREDDER;
        break;
        
    case STAGEID::ID_ST42NB:
    case STAGEID::ID_ST60X_B10:
        enemyId = ENEMYID::ID_LEATHER_HEAD;
        break;
        
    case STAGEID::ID_ST44NB:
    case STAGEID::ID_ST60X_D05:
        enemyId = ENEMYID::ID_ULTIMATE_NINJA;
        break;
        
    case STAGEID::ID_ST47OB:
    case STAGEID::ID_ST60X_C08:
        enemyId = ENEMYID::ID_FOOT_MECH_SPLINTER;
        break;
        
    case STAGEID::ID_ST52FB:
    case STAGEID::ID_ST60X_C07:
        enemyId = ENEMYID::ID_ELITE_FOOT_A;
        break;
        
    case STAGEID::ID_ST53FB:
        enemyId = ENEMYID::ID_ELITE_FOOT_B;
        break;

    case STAGEID::ID_ST54FB:
    case STAGEID::ID_ST60X_C04:
        enemyId = ENEMYID::ID_ELITE_FOOT_C;
        break;
        
    case STAGEID::ID_ST55FB:
    case STAGEID::ID_ST60X_C02:
        enemyId = ENEMYID::ID_ELITE_FOOT_D;
        break;
        
    case STAGEID::ID_ST56NB:
    case STAGEID::ID_ST60X_C06:
        enemyId = ENEMYID::ID_HUN_B;
        break;
        
    case STAGEID::ID_ST57NB:
    case STAGEID::ID_ST60X_C09:
        enemyId = ENEMYID::ID_KARAI;
        break;
        
    case STAGEID::ID_ST58OB1:
    case STAGEID::ID_ST58OB2:
    case STAGEID::ID_ST60X_C10:
        enemyId = ENEMYID::ID_ULTIMATE_SHREDDER;
        break;
        
    case STAGEID::ID_ST60X_D07:
        enemyId = ENEMYID::ID_SPLINTER;
        break;
        
    case STAGEID::ID_ST60X_D09:
        enemyId = ENEMYID::ID_MIYAMOTO_USAGI;
        break;
        
    case STAGEID::ID_ST60X_D10:
        enemyId = ENEMYID::ID_DORAKO;
        break;

    default:
        break;
    };

    return enemyId;
};


/*static*/ bool CStageInfo::IsBossGaugeNecessary(STAGEID::VALUE idStage)
{
    ENEMYID::VALUE enemyId = GetGaugeEnemyID(idStage, 0);
    return (enemyId != ENEMYID::ID_DUMMY);
};


/*static*/ MOVIEID::VALUE CStageInfo::GetStageInMovieID(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST01T:
        return MOVIEID::VALUE(2);
        
    case STAGEID::ID_ST02NB:
        return MOVIEID::VALUE(3);
        
    case STAGEID::ID_ST04N:
        return MOVIEID::VALUE(6);
        
    case STAGEID::ID_ST09N:
        return MOVIEID::VALUE(10);
        
    case STAGEID::ID_ST10N:
        return MOVIEID::VALUE(11);
        
    case STAGEID::ID_ST12N:
        return MOVIEID::VALUE(13);
        
    case STAGEID::ID_ST15N:
        return MOVIEID::VALUE(15);
        
    case STAGEID::ID_ST17N:
        return MOVIEID::VALUE(16);
        
    case STAGEID::ID_ST18FB:
        return MOVIEID::VALUE(17);
        
    case STAGEID::ID_ST19N:
        return MOVIEID::VALUE(19);
        
    case STAGEID::ID_ST20FB:
        return MOVIEID::VALUE(20);
        
    case STAGEID::ID_ST21NB:
        return MOVIEID::VALUE(22);
        
    case STAGEID::ID_ST24N:
        return MOVIEID::VALUE(24);
        
    case STAGEID::ID_ST25J:
        return MOVIEID::VALUE(26);
        
    case STAGEID::ID_ST29N:
        return MOVIEID::VALUE(28);
        
    case STAGEID::ID_ST30NB:
        return MOVIEID::VALUE(30);
        
    case STAGEID::ID_ST31NB:
        return MOVIEID::VALUE(32);
        
    case STAGEID::ID_ST33J:
        return MOVIEID::VALUE(35);
        
    case STAGEID::ID_ST38NB:
        return MOVIEID::VALUE(36);
        
    case STAGEID::ID_ST39N:
        return MOVIEID::VALUE(38);
        
    case STAGEID::ID_ST40OB:
        return MOVIEID::VALUE(39);
        
    case STAGEID::ID_ST41N:
        return MOVIEID::VALUE(41);
        
    case STAGEID::ID_ST42NB:
        return MOVIEID::VALUE(42);
        
    case STAGEID::ID_ST43N:
        return MOVIEID::VALUE(44);
        
    case STAGEID::ID_ST44NB:
        return MOVIEID::VALUE(45);
        
    case STAGEID::ID_ST45N:
        return MOVIEID::VALUE(47);
        
    case STAGEID::ID_ST47OB:
        return MOVIEID::VALUE(50);
        
    case STAGEID::ID_ST48N:
        return MOVIEID::VALUE(52);
        
    case STAGEID::ID_ST50NB:
        return MOVIEID::VALUE(53);
        
    case STAGEID::ID_ST52FB:
        return MOVIEID::VALUE(56);
        
    case STAGEID::ID_ST53FB:
        return MOVIEID::VALUE(58);
        
    case STAGEID::ID_ST54FB:
        return MOVIEID::VALUE(60);
        
    case STAGEID::ID_ST55FB:
        return MOVIEID::VALUE(62);
        
    case STAGEID::ID_ST56NB:
        return MOVIEID::VALUE(64);
        
    case STAGEID::ID_ST57NB:
        return MOVIEID::VALUE(66);
        
    case STAGEID::ID_ST58OB1:
        return MOVIEID::VALUE(68);
        
    case STAGEID::ID_ST58OB2:
        return MOVIEID::VALUE(69);
        
    case STAGEID::ID_ST60X_D01:
        return MOVIEID::VALUE(71);
        
    case STAGEID::ID_ST60X_D04:
        return MOVIEID::VALUE(72);
        
    case STAGEID::ID_ST60X_D08:
        return MOVIEID::VALUE(73);
        
    case STAGEID::ID_ST60X_D09:
        return MOVIEID::VALUE(74);
        
    case STAGEID::ID_ST60X_D10:        
        return MOVIEID::VALUE(75);
        
    default:
        return MOVIEID::ID_MAX;
    };
};


/*static*/ bool CStageInfo::IsPlayMovieOfStageIn(STAGEID::VALUE idStage)
{
    MOVIEID::VALUE movieId = GetStageInMovieID(idStage);
    return (movieId != MOVIEID::ID_MAX);
};


/*static*/ MOVIEID::VALUE CStageInfo::GetStageOutMovieID(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST02NB:
        return MOVIEID::VALUE(4);

    case STAGEID::ID_ST04NB:
        return MOVIEID::VALUE(7);

    case STAGEID::ID_ST05N:
        return MOVIEID::VALUE(8);

    case STAGEID::ID_ST18FB:
        return MOVIEID::VALUE(18);

    case STAGEID::ID_ST20FB:
        return MOVIEID::VALUE(21);

    case STAGEID::ID_ST50NB:
        return MOVIEID::VALUE(54);

    case STAGEID::ID_ST52FB:
        return MOVIEID::VALUE(57);

    case STAGEID::ID_ST53FB:
        return MOVIEID::VALUE(59);

    case STAGEID::ID_ST54FB:
        return MOVIEID::VALUE(61);

    case STAGEID::ID_ST55FB:
        return MOVIEID::VALUE(63);

    case STAGEID::ID_ST56NB:
        return MOVIEID::VALUE(65);

    case STAGEID::ID_ST60X_D09:
        return MOVIEID::VALUE(76);

    default:
        return MOVIEID::ID_MAX;
    };
};


/*static*/ bool CStageInfo::IsPlayMovieOfStageOut(STAGEID::VALUE idStage)
{
    MOVIEID::VALUE movieId = GetStageOutMovieID(idStage);
    return (movieId != MOVIEID::ID_MAX);
};

