#include "StageInfo.hpp"


struct STAGEINFO
{
    const char*              m_pszName;
    FNAME                    m_iFileID;
    MAPID::VALUE             m_MapID;
    int32                    m_iBgmNo;
    AREAID::VALUE            m_AreaID;
    GAMETYPES::STAGEMODE     m_mode;
    CStageInfo::CAMERAUPDATE m_cameraupdate;
    CStageInfo::IMPLEMENT    m_implement;
};


static const STAGEINFO s_aStageInfo[] =
{
    //
    //  Normal
    //
    { "NONE",    FNAME_INVALID,                      MAPID::ID_NONE,     SDCODE_BGM(0x3000),     AREAID::ID_NONE,    GAMETYPES::STAGEMODE_NONE,      CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST01T",   FPATH("Common/Stage/ST01T.lpac"),   MAPID::ID_M01T,     SDCODE_BGM(0x3000),     AREAID::ID_AREA01,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST02N",   FPATH("Common/Stage/ST02N.lpac"),   MAPID::ID_M02N,     SDCODE_BGM(0x3000),     AREAID::ID_AREA02,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST02NB",  FPATH("Common/Stage/ST02NB.lpac"),  MAPID::ID_M02NB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA02,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST03S",   FPATH("Common/Stage/ST03S.lpac"),   MAPID::ID_M03S,     SDCODE_BGM(0x3014),     AREAID::ID_AREA03,  GAMETYPES::STAGEMODE_HOME,      CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST04N",   FPATH("Common/Stage/ST04N.lpac"),   MAPID::ID_M04N,     SDCODE_BGM(0x3001),     AREAID::ID_AREA04,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST04NB",  FPATH("Common/Stage/ST04NB.lpac"),  MAPID::ID_M04NB,    SDCODE_BGM(0x3001),     AREAID::ID_AREA04,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST05N",   FPATH("Common/Stage/ST05N.lpac"),   MAPID::ID_M05N,     SDCODE_BGM(0x3001),     AREAID::ID_AREA05,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST06R",   FPATH("Common/Stage/ST06R.lpac"),   MAPID::ID_M06R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA06,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,       CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST09N",   FPATH("Common/Stage/ST09N.lpac"),   MAPID::ID_M09N,     SDCODE_BGM(0x3002),     AREAID::ID_AREA09,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST10N",   FPATH("Common/Stage/ST10N.lpac"),   MAPID::ID_M10N,     SDCODE_BGM(0x3002),     AREAID::ID_AREA10,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST11J",   FPATH("Common/Stage/ST11J.lpac"),   MAPID::ID_M11J,     SDCODE_BGM(0x3002),     AREAID::ID_AREA11,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST12N",   FPATH("Common/Stage/ST12N.lpac"),   MAPID::ID_M12N,     SDCODE_BGM(0x3003),     AREAID::ID_AREA12,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST13R",   FPATH("Common/Stage/ST13R.lpac"),   MAPID::ID_M13R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA13,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,       CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST14N",   FPATH("Common/Stage/ST14N.lpac"),   MAPID::ID_M14N,     SDCODE_BGM(0x3003),     AREAID::ID_AREA14,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST15N",   FPATH("Common/Stage/ST15N.lpac"),   MAPID::ID_M15N,     SDCODE_BGM(0x3004),     AREAID::ID_AREA15,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST17N",   FPATH("Common/Stage/ST17N.lpac"),   MAPID::ID_M17N,     SDCODE_BGM(0x301B),     AREAID::ID_AREA17,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST18F",   FPATH("Common/Stage/ST18F.lpac"),   MAPID::ID_M18F,     SDCODE_BGM(0x3005),     AREAID::ID_AREA18,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST18FB",  FPATH("Common/Stage/ST18FB.lpac"),  MAPID::ID_M18FB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA18,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST19N",   FPATH("Common/Stage/ST19N.lpac"),   MAPID::ID_M19N,     SDCODE_BGM(0x3006),     AREAID::ID_AREA19,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST20F",   FPATH("Common/Stage/ST20F.lpac"),   MAPID::ID_M20F,     SDCODE_BGM(0x3006),     AREAID::ID_AREA20,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST20FB",  FPATH("Common/Stage/ST20FB.lpac"),  MAPID::ID_M20FB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA20,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST21N",   FPATH("Common/Stage/ST21N.lpac"),   MAPID::ID_M21N,     SDCODE_BGM(0x3007),     AREAID::ID_AREA21,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST21NB",  FPATH("Common/Stage/ST21NB.lpac"),  MAPID::ID_M21NB,    SDCODE_BGM(0x301D),     AREAID::ID_AREA21,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST22R",   FPATH("Common/Stage/ST22R.lpac"),   MAPID::ID_M22R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA22,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,       CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST23N",   FPATH("Common/Stage/ST23N.lpac"),   MAPID::ID_M23N,     SDCODE_BGM(0x3008),     AREAID::ID_AREA23,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST24N",   FPATH("Common/Stage/ST24N.lpac"),   MAPID::ID_M24N,     SDCODE_BGM(0x3009),     AREAID::ID_AREA24,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST25J",   FPATH("Common/Stage/ST25J.lpac"),   MAPID::ID_M25J,     SDCODE_BGM(0x300A),     AREAID::ID_AREA25,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST26N",   FPATH("Common/Stage/ST26N.lpac"),   MAPID::ID_M26N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA26,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST27N",   FPATH("Common/Stage/ST27N.lpac"),   MAPID::ID_M27N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA27,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST28N",   FPATH("Common/Stage/ST28N.lpac"),   MAPID::ID_M28N,     SDCODE_BGM(0x300A),     AREAID::ID_AREA28,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST29N",   FPATH("Common/Stage/ST29N.lpac"),   MAPID::ID_M29N,     SDCODE_BGM(0x300B),     AREAID::ID_AREA29,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST30N",   FPATH("Common/Stage/ST30N.lpac"),   MAPID::ID_M30N,     SDCODE_BGM(0x300B),     AREAID::ID_AREA30,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST30NB",  FPATH("Common/Stage/ST30NB.lpac"),  MAPID::ID_M30NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA30,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST31NB",  FPATH("Common/Stage/ST31NB.lpac"),  MAPID::ID_M31NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA31,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST32R",   FPATH("Common/Stage/ST32R.lpac"),   MAPID::ID_M32R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA32,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,       CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST33J",   FPATH("Common/Stage/ST33J.lpac"),   MAPID::ID_M33J,     SDCODE_BGM(0x300C),     AREAID::ID_AREA33,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST34N",   FPATH("Common/Stage/ST34N.lpac"),   MAPID::ID_M34N,     SDCODE_BGM(0x300D),     AREAID::ID_AREA34,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST35N",   FPATH("Common/Stage/ST35N.lpac"),   MAPID::ID_M35N,     SDCODE_BGM(0x300D),     AREAID::ID_AREA35,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST36N",   FPATH("Common/Stage/ST36N.lpac"),   MAPID::ID_M36N,     SDCODE_BGM(0x300C),     AREAID::ID_AREA36,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST37N",   FPATH("Common/Stage/ST37N.lpac"),   MAPID::ID_M37N,     SDCODE_BGM(0x300C),     AREAID::ID_AREA37,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST38NB",  FPATH("Common/Stage/ST38NB.lpac"),  MAPID::ID_M38NB,    SDCODE_BGM(0x3019),     AREAID::ID_AREA38,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST39N",   FPATH("Common/Stage/ST39N.lpac"),   MAPID::ID_M39N,     SDCODE_BGM(0x300E),     AREAID::ID_AREA39,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST40OB",  FPATH("Common/Stage/ST40OB.lpac"),  MAPID::ID_M40OB,    SDCODE_BGM(0x3019),     AREAID::ID_AREA40,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST41N",   FPATH("Common/Stage/ST41N.lpac"),   MAPID::ID_M41N,     SDCODE_BGM(0x300F),     AREAID::ID_AREA41,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST42NB",  FPATH("Common/Stage/ST42NB.lpac"),  MAPID::ID_M42NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA42,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST43N",   FPATH("Common/Stage/ST43N.lpac"),   MAPID::ID_M43N,     SDCODE_BGM(0x3010),     AREAID::ID_AREA43,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST44N",   FPATH("Common/Stage/ST44N.lpac"),   MAPID::ID_M44N,     SDCODE_BGM(0x3010),     AREAID::ID_AREA44,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST44NB",  FPATH("Common/Stage/ST44NB.lpac"),  MAPID::ID_M44NB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA44,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST45N",   FPATH("Common/Stage/ST45N.lpac"),   MAPID::ID_M45N,     SDCODE_BGM(0x3011),     AREAID::ID_AREA45,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST46R",   FPATH("Common/Stage/ST46R.lpac"),   MAPID::ID_M46R,     SDCODE_BGM(0x3015),     AREAID::ID_AREA46,  GAMETYPES::STAGEMODE_RIDE,      CStageInfo::CAMERAUPDATE_RIDE,       CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST47O",   FPATH("Common/Stage/ST47O.lpac"),   MAPID::ID_M47O,     SDCODE_BGM(0x3011),     AREAID::ID_AREA47,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST47OB",  FPATH("Common/Stage/ST47OB.lpac"),  MAPID::ID_M47OB,    SDCODE_BGM(0x3016),     AREAID::ID_AREA47,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST48N",   FPATH("Common/Stage/ST48N.lpac"),   MAPID::ID_M48N,     SDCODE_BGM(0x3012),     AREAID::ID_AREA48,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST49N",   FPATH("Common/Stage/ST49N.lpac"),   MAPID::ID_M49N,     SDCODE_BGM(0x3012),     AREAID::ID_AREA49,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST50NB",  FPATH("Common/Stage/ST50NB.lpac"),  MAPID::ID_M50NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA50,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST52F",   FPATH("Common/Stage/ST52F.lpac"),   MAPID::ID_M52F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA52,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST52FB",  FPATH("Common/Stage/ST52FB.lpac"),  MAPID::ID_M52FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA52,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST53F",   FPATH("Common/Stage/ST53F.lpac"),   MAPID::ID_M53F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA53,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST53FB",  FPATH("Common/Stage/ST53FB.lpac"),  MAPID::ID_M53FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA53,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST54F",   FPATH("Common/Stage/ST54F.lpac"),   MAPID::ID_M54F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA54,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST54FB",  FPATH("Common/Stage/ST54FB.lpac"),  MAPID::ID_M54FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA54,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST55F",   FPATH("Common/Stage/ST55F.lpac"),   MAPID::ID_M55F,     SDCODE_BGM(0x3013),     AREAID::ID_AREA55,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST55FB",  FPATH("Common/Stage/ST55FB.lpac"),  MAPID::ID_M55FB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA55,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_NORMAL,     CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST56NB",  FPATH("Common/Stage/ST56NB.lpac"),  MAPID::ID_M56NB,    SDCODE_BGM(0x3017),     AREAID::ID_AREA56,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST57NB",  FPATH("Common/Stage/ST57NB.lpac"),  MAPID::ID_M57NB,    SDCODE_BGM(0x3018),     AREAID::ID_AREA57,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST58OB1", FPATH("Common/Stage/ST58OB1.lpac"), MAPID::ID_M58O,     SDCODE_BGM(0x3019),     AREAID::ID_AREA58,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST58OB2", FPATH("Common/Stage/ST58OB2.lpac"), MAPID::ID_M58OB,    SDCODE_BGM(0x301A),     AREAID::ID_AREA58,  GAMETYPES::STAGEMODE_NORMAL,    CStageInfo::CAMERAUPDATE_BOSSBATTLE, CStageInfo::IMPLEMENT_ENABLEPLAY },

    //
    //  Kitty
    //
    { "ST60X_A01", FPATH("Common/Stage/ST60X_A01.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A02", FPATH("Common/Stage/ST60X_A02.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A03", FPATH("Common/Stage/ST60X_A03.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A04", FPATH("Common/Stage/ST60X_A04.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A05", FPATH("Common/Stage/ST60X_A05.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A06", FPATH("Common/Stage/ST60X_A06.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A07", FPATH("Common/Stage/ST60X_A07.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A08", FPATH("Common/Stage/ST60X_A08.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A09", FPATH("Common/Stage/ST60X_A09.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_A10", FPATH("Common/Stage/ST60X_A10.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_A, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },

    //
    //  Monster
    //
    { "ST60X_B01", FPATH("Common/Stage/ST60X_B01.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B02", FPATH("Common/Stage/ST60X_B02.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B03", FPATH("Common/Stage/ST60X_B03.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B04", FPATH("Common/Stage/ST60X_B04.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B05", FPATH("Common/Stage/ST60X_B05.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B06", FPATH("Common/Stage/ST60X_B06.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B07", FPATH("Common/Stage/ST60X_B07.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B08", FPATH("Common/Stage/ST60X_B08.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B09", FPATH("Common/Stage/ST60X_B09.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_B10", FPATH("Common/Stage/ST60X_B10.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_B, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },

    //
    //  Foot
    //
    { "ST60X_C01", FPATH("Common/Stage/ST60X_C01.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C02", FPATH("Common/Stage/ST60X_C02.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C03", FPATH("Common/Stage/ST60X_C03.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C04", FPATH("Common/Stage/ST60X_C04.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C05", FPATH("Common/Stage/ST60X_C05.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C06", FPATH("Common/Stage/ST60X_C06.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C07", FPATH("Common/Stage/ST60X_C07.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C08", FPATH("Common/Stage/ST60X_C08.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C09", FPATH("Common/Stage/ST60X_C09.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_C10", FPATH("Common/Stage/ST60X_C10.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301E), AREAID::ID_AREA60_C, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },

    //
    //  Battle Nexus
    //
    { "ST60X_D01", FPATH("Common/Stage/ST60X_D01.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D02", FPATH("Common/Stage/ST60X_D02.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D03", FPATH("Common/Stage/ST60X_D03.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D04", FPATH("Common/Stage/ST60X_D04.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D05", FPATH("Common/Stage/ST60X_D05.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D06", FPATH("Common/Stage/ST60X_D06.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D07", FPATH("Common/Stage/ST60X_D07.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D08", FPATH("Common/Stage/ST60X_D08.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D09", FPATH("Common/Stage/ST60X_D09.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
    { "ST60X_D10", FPATH("Common/Stage/ST60X_D10.lpac"), MAPID::ID_M60X, SDCODE_BGM(0x301F), AREAID::ID_AREA60_D, GAMETYPES::STAGEMODE_NEXUS, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },

    //
    //  Misc
    //
#ifdef _DEBUG    
    { "STTEST",    FPATH("Common/Stage/ST03S.lpac"),    MAPID::ID_TEST, 0, AREAID::ID_NONE, GAMETYPES::STAGEMODE_NONE, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_ENABLEPLAY },
#else /* _DEBUG */
    { "STTEST",    FNAME_INVALID,                       MAPID::ID_TEST, 0, AREAID::ID_NONE, GAMETYPES::STAGEMODE_NONE, CStageInfo::CAMERAUPDATE_NORMAL, CStageInfo::IMPLEMENT_NOIMPL },
#endif /* _DEBUG */
};


static_assert(COUNT_OF(s_aStageInfo) == STAGEID::ID_MAX, "update me");


static const STAGEINFO& StageInfo(STAGEID::VALUE idStage)
{    
    ASSERT(idStage >= STAGEID::ID_NONE);
    ASSERT(idStage < STAGEID::ID_MAX);

    return s_aStageInfo[idStage];
};


/*static*/ FNAME CStageInfo::GetFileID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_iFileID;
};


/*static*/ MAPID::VALUE CStageInfo::GetMapID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_MapID;
};


/*static*/ int32 CStageInfo::GetBgmNo(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_iBgmNo;
};


/*static*/ AREAID::VALUE CStageInfo::GetAreaID(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_AreaID;
};


/*static*/ GAMETYPES::STAGEMODE CStageInfo::GetMode(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_mode;
};


/*static*/ float CStageInfo::GetEnemyAppearDistance(STAGEID::VALUE idStage)
{
    if (idStage == STAGEID::ID_ST31NB)   // spasmosaur area
        return 200.0f;
    
    return 25.0f;
};


/*static*/ CStageInfo::CAMERAUPDATE CStageInfo::GetCameraUpdateType(STAGEID::VALUE idStage)
{
    return StageInfo(idStage).m_cameraupdate;
};


/*static*/ float CStageInfo::GetObjectSleepDistance(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST23N:
        return 80.0f;

    case STAGEID::ID_ST34N:
    case STAGEID::ID_ST44NB:
        return 60.0f;

    case STAGEID::ID_ST52F:
    case STAGEID::ID_ST53F:
        return 50.0f;

    case STAGEID::ID_ST31NB:
        return 500.0f;

    default:
        return 40.0f;
    };
};


/*static*/ ENEMYID::VALUE CStageInfo::GetGaugeEnemyID(STAGEID::VALUE idStage, int32 iEnemyIndex)
{
    ENEMYID::VALUE enemyId = ENEMYID::ID_DUMMY;

    if (iEnemyIndex)
    {
        if ((idStage == STAGEID::ID_ST60X_C07) && (iEnemyIndex == 1))
            enemyId = ENEMYID::ID_ELITE_FOOT_B;

        return enemyId;
    };

    switch (idStage)
    {
#ifdef _DEBUG
    case STAGEID::ID_STTEST:
        enemyId = ENEMYID::ID_KARAI;
        break;
#endif /* _DEBUG */
        
    case STAGEID::ID_ST02NB:
        enemyId = ENEMYID::ID_HUN_A;
        break;

    case STAGEID::ID_ST18FB:
    case STAGEID::ID_ST60X_D04:
        enemyId = ENEMYID::ID_NINJA_RATS_A;
        break;
        
    case STAGEID::ID_ST20FB:
    case STAGEID::ID_ST50NB:
    case STAGEID::ID_ST60X_D08:
        enemyId = ENEMYID::ID_SLASSHUR;
        break;
        
    case STAGEID::ID_ST30NB:
    case STAGEID::ID_ST60X_D03:
        enemyId = ENEMYID::ID_TRAXIMUS;
        break;
        
    case STAGEID::ID_ST31NB:
        enemyId = ENEMYID::ID_SPASMOSAUR;
        break;
        
    case STAGEID::ID_ST38NB:
        enemyId = ENEMYID::ID_FEUDAL_JAPAN_SHREDDER;
        break;
        
    case STAGEID::ID_ST42NB:
    case STAGEID::ID_ST60X_B10:
        enemyId = ENEMYID::ID_LEATHER_HEAD;
        break;
        
    case STAGEID::ID_ST44NB:
    case STAGEID::ID_ST60X_D05:
        enemyId = ENEMYID::ID_ULTIMATE_NINJA;
        break;
        
    case STAGEID::ID_ST47OB:
    case STAGEID::ID_ST60X_C08:
        enemyId = ENEMYID::ID_FOOT_MECH_SPLINTER;
        break;
        
    case STAGEID::ID_ST52FB:
    case STAGEID::ID_ST60X_C07:
        enemyId = ENEMYID::ID_ELITE_FOOT_A;
        break;
        
    case STAGEID::ID_ST53FB:
        enemyId = ENEMYID::ID_ELITE_FOOT_B;
        break;

    case STAGEID::ID_ST54FB:
    case STAGEID::ID_ST60X_C04:
        enemyId = ENEMYID::ID_ELITE_FOOT_C;
        break;
        
    case STAGEID::ID_ST55FB:
    case STAGEID::ID_ST60X_C02:
        enemyId = ENEMYID::ID_ELITE_FOOT_D;
        break;
        
    case STAGEID::ID_ST56NB:
    case STAGEID::ID_ST60X_C06:
        enemyId = ENEMYID::ID_HUN_B;
        break;
        
    case STAGEID::ID_ST57NB:
    case STAGEID::ID_ST60X_C09:
        enemyId = ENEMYID::ID_KARAI;
        break;
        
    case STAGEID::ID_ST58OB1:
    case STAGEID::ID_ST58OB2:
    case STAGEID::ID_ST60X_C10:
        enemyId = ENEMYID::ID_ULTIMATE_SHREDDER;
        break;
        
    case STAGEID::ID_ST60X_D07:
        enemyId = ENEMYID::ID_SPLINTER;
        break;
        
    case STAGEID::ID_ST60X_D09:
        enemyId = ENEMYID::ID_MIYAMOTO_USAGI;
        break;
        
    case STAGEID::ID_ST60X_D10:
        enemyId = ENEMYID::ID_DORAKO;
        break;

    default:
        break;
    };

    return enemyId;
};


/*static*/ bool CStageInfo::IsBossGaugeNecessary(STAGEID::VALUE idStage)
{
    ENEMYID::VALUE enemyId = GetGaugeEnemyID(idStage, 0);
    return (enemyId != ENEMYID::ID_DUMMY);
};


/*static*/ MVNAME CStageInfo::GetStageInMovieID(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST01T:
        return MVPATH("m01t01.sfd");
        
    case STAGEID::ID_ST02NB:
        return MVPATH("m02n01.sfd");
        
    case STAGEID::ID_ST04N:
        return MVPATH("m04n01.sfd");
        
    case STAGEID::ID_ST09N:
        return MVPATH("m09n01.sfd");
        
    case STAGEID::ID_ST10N:
        return MVPATH("m10n01.sfd");
        
    case STAGEID::ID_ST12N:
        return MVPATH("m12n01.sfd");
        
    case STAGEID::ID_ST15N:
        return MVPATH("m15n01.sfd");
        
    case STAGEID::ID_ST17N:
        return MVPATH("m17n01.sfd");
        
    case STAGEID::ID_ST18FB:
        return MVPATH("m18fb01.sfd");
        
    case STAGEID::ID_ST19N:
        return MVPATH("m19n01p.sfd");
        
    case STAGEID::ID_ST20FB:
        return MVPATH("m20fb01.sfd");
        
    case STAGEID::ID_ST21NB:
        return MVPATH("m21n01.sfd");
        
    case STAGEID::ID_ST24N:
        return MVPATH("m24n01.sfd");
        
    case STAGEID::ID_ST25J:
        return MVPATH("m25j01.sfd");
        
    case STAGEID::ID_ST29N:
        return MVPATH("m29n01.sfd");
        
    case STAGEID::ID_ST30NB:
        return MVPATH("m30nb01p.sfd");
        
    case STAGEID::ID_ST31NB:
        return MVPATH("m31nb01p.sfd");
        
    case STAGEID::ID_ST33J:
        return MVPATH("m33j01.sfd");
        
    case STAGEID::ID_ST38NB:
        return MVPATH("m38nb01.sfd");
        
    case STAGEID::ID_ST39N:
        return MVPATH("m39n01.sfd");
        
    case STAGEID::ID_ST40OB:
        return MVPATH("m40ob01.sfd");
        
    case STAGEID::ID_ST41N:
        return MVPATH("m41nb01.sfd");
        
    case STAGEID::ID_ST42NB:
        return MVPATH("m42nb01p.sfd");
        
    case STAGEID::ID_ST43N:
        return MVPATH("m43n01.sfd");
        
    case STAGEID::ID_ST44NB:
        return MVPATH("m44nb01p.sfd");
        
    case STAGEID::ID_ST45N:
        return MVPATH("m45n01.sfd");
        
    case STAGEID::ID_ST47OB:
        return MVPATH("m47ob01.sfd");
        
    case STAGEID::ID_ST48N:
        return MVPATH("m48n01.sfd");
        
    case STAGEID::ID_ST50NB:
        return MVPATH("m50nb01.sfd");
        
    case STAGEID::ID_ST52FB:
        return MVPATH("m52fb01p.sfd");
        
    case STAGEID::ID_ST53FB:
        return MVPATH("m53fb01p.sfd");
        
    case STAGEID::ID_ST54FB:
        return MVPATH("m54fb01p.sfd");
        
    case STAGEID::ID_ST55FB:
        return MVPATH("m55fb01p.sfd");
        
    case STAGEID::ID_ST56NB:
        return MVPATH("m56nb01.sfd");
        
    case STAGEID::ID_ST57NB:
        return MVPATH("m57nb01.sfd");
        
    case STAGEID::ID_ST58OB1:
        return MVPATH("m58ob01.sfd");
        
    case STAGEID::ID_ST58OB2:
        return MVPATH("m58ob02.sfd");
        
    case STAGEID::ID_ST60X_D01:
        return MVPATH("m59s01.sfd");
        
    case STAGEID::ID_ST60X_D04:
        return MVPATH("m59s02.sfd");
        
    case STAGEID::ID_ST60X_D08:
        return MVPATH("m59s03.sfd");
        
    case STAGEID::ID_ST60X_D09:
        return MVPATH("m60x01p.sfd");
        
    case STAGEID::ID_ST60X_D10:        
        return MVPATH("m60x02p.sfd");
        
    default:
        return MVNAME_INVALID;
    };
};


/*static*/ bool CStageInfo::IsPlayMovieOfStageIn(STAGEID::VALUE idStage)
{
    return (!MVNAME_EQUAL(GetStageInMovieID(idStage), MVNAME_INVALID));
};


/*static*/ MVNAME CStageInfo::GetStageOutMovieID(STAGEID::VALUE idStage)
{
    switch (idStage)
    {
    case STAGEID::ID_ST02NB:
        return MVPATH("m02n01p.sfd");

    case STAGEID::ID_ST04NB:
        return MVPATH("m04n01p.sfd");

    case STAGEID::ID_ST05N:
        return MVPATH("m05n01p.sfd");

    case STAGEID::ID_ST18FB:
        return MVPATH("m18fb02.sfd");

    case STAGEID::ID_ST20FB:
        return MVPATH("m20fb02.sfd");

    case STAGEID::ID_ST50NB:
        return MVPATH("m50nb01p.sfd");

    case STAGEID::ID_ST52FB:
        return MVPATH("m52fb02p.sfd");

    case STAGEID::ID_ST53FB:
        return MVPATH("m53fb02p.sfd");

    case STAGEID::ID_ST54FB:
        return MVPATH("m54fb02p.sfd");

    case STAGEID::ID_ST55FB:
        return MVPATH("m55fb02p.sfd");

    case STAGEID::ID_ST56NB:
        return MVPATH("m56nb01p.sfd");

    case STAGEID::ID_ST60X_D09:
        return MVPATH("m60x03p.sfd");

    default:
        return MVNAME_INVALID;
    };
};


/*static*/ bool CStageInfo::IsPlayMovieOfStageOut(STAGEID::VALUE idStage)
{
    return (!MVNAME_EQUAL(GetStageOutMovieID(idStage), MVNAME_INVALID));
};


/*static*/ CStageInfo::IMPLEMENT CStageInfo::GetImplementProgress(STAGEID::VALUE idStage)
{
	return StageInfo(idStage).m_implement;
};