set(DXSDK_ROOT_DIR "$ENV{DXSDK_DIR}")

find_path(DXSDK_INCLUDE_DIR d3d9.h
    PATHS "${DXSDK_ROOT_DIR}/Include"
    DOC "DirectX SDK include directory"
)

set(DXSDK_LIB_PATH "${DXSDK_ROOT_DIR}/Lib/x86")

find_library(DXSDK_D3D9_LIBRARY     NAMES d3d9.lib      PATHS "${DXSDK_LIB_PATH}" NO_DEFAULT_PATH)
find_library(DXSDK_DINPUT8_LIBRARY  NAMES dinput8.lib   PATHS "${DXSDK_LIB_PATH}" NO_DEFAULT_PATH)
find_library(DXSDK_DXGUID_LIBRARY   NAMES dxguid.lib    PATHS "${DXSDK_LIB_PATH}" NO_DEFAULT_PATH)
find_library(DXSDK_DSOUND_LIBRARY   NAMES dsound.lib    PATHS "${DXSDK_LIB_PATH}" NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DXSDK DEFAULT_MSG 
    DXSDK_D3D9_LIBRARY 
    DXSDK_INCLUDE_DIR
)

if(DXSDK_FOUND)
    add_library(DXSDK::DXSDK INTERFACE IMPORTED)
    set_target_properties(DXSDK::DXSDK PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${DXSDK_INCLUDE_DIR}"
        INTERFACE_LINK_LIBRARIES "${DXSDK_D3D9_LIBRARY};${DXSDK_DINPUT8_LIBRARY};${DXSDK_DXGUID_LIBRARY};${DXSDK_DSOUND_LIBRARY}"
    )
endif()